- key: numbers
  title: Zahlen
  description: Übe die Grundlagen der Programmierung mit einfachen Aufgaben.
  # icon: /images/rocket.png
  entries:
    - add_numbers
    - even
    - max_of_two
    - factorial
    - fibonacci
    - gcd
    - prime
    - find_missing_number
    - primegen
    # - array_sum

    # - two_sum
    # - reverse_array
- key: strings
  title: Strings
  description: Arbeite mit Zeichenketten und übe String-Manipulation.
  # icon: /images/rocket.png
  entries:
    - reverse_string
    # - palindrome
    # - count_vowels