- key: basics
  title: Basics
  description: Ãœbe die Grundlagen der Programmierung mit einfachen Aufgaben.
  icon: /images/rocket.png
  entries:
    - add_numbers
    - even
    - max_of_two
    # - array_sum

    # - two_sum
    # - reverse_array
